### ISSUE TITLE
Standalone File Manger v1.39 and 1.40 freezing.

### ISSUE THREAD

**Issue by 60fpshacksrock** [Zarh/ManaGunZ#61]
It happens when exiting after transferring file to/from PS3 HDD and USB flash drive.
No problems though with 1.38.

PS3 CFW is REBUG COBRA 4.86.1 LITE

**Comment by rhynec** [comment]
Is your USB flash drive formatted to NTFS or exFAT? The problem may have been fixed in this commit: https://github.com/Zarh/ManaGunZ/commit/69537e83ec2088e0caa46960bea441c09ab22233, which was a fix for this issue: https://github.com/Zarh/ManaGunZ/issues/55. The fix is only present in the pre-release v1.41, which doesn't have a standalone file manager pkg built (you could ask @Zarh to build you one to test). Could you first test the pre-release v1.41 (full)? Maybe also test the full v1.40 to check whether it's an issue with only the standalone file manager or not.

**Comment by 60fpshacksrock** [comment]
Could I get a link to 1.41?

**Comment by rhynec** [comment]
It seems the final v1.41 will be released shortly, since Zar pushed this commit a few hours ago: https://github.com/Zarh/ManaGunZ/commit/610f9cbbfa633ca30071513d2b353e5bb4f3f689. Just wait for the final version to be released and test.

**Comment by Zarh** [comment]
I'm going to try to reproduce your issue. What did you copy ? A directory ? A file ? And where did copy it, fat32, ntfs, exFat ?

I didn't test the 1.41 yet. So, it's not ready to be released.

**Comment by 60fpshacksrock** [comment]
I honestly cannot remember. I have two drives, one is FAT32, the other NTFS.

**Comment by 60fpshacksrock** [comment]
As I said in the other post, 1,41 File Manager is still freezing.

**Comment by Syrus-33** [comment]
1.41 file manager still freezing for me as well usb ntfs

**Comment by Zarh** [comment]
I'll try to fix this major issue today. I hope, I'll be able to upload a pre-release pkg this evening. Sorry, about the trouble.

**Comment by Syrus-33** [comment]
No trouble, your work is great. Just has a hiccup.

**Comment by Zarh** [comment]
Can you please tell me step by step what you did before the freeze from a fresh installation of the pkg ?

I tryed to copy big files a big files 4.75GB, small one 300MB a directory with lot of files (8GB), I tried the filemanager v1.40

My hdd is an NTFS (MBR) 300GB

**Comment by Syrus-33** [comment]
I'm using a 32gb USB ntfs, plug the USB then open managunz, open file manager. I have tried with several different tile sizes. This doesn't seem to make a difference.

After I copy the files I press O to exit and it just freezes. Have to turn off the ps3 with the power button.

Sometimes if I repeatedly press O fast it will exit normally. 30% of the time.

I will try to take a video tonight.

**Comment by Zarh** [comment]
So, i tried with Filemanager 1.40 with usb HDD and an usb stick like 10 times, still not a single freeze. Do you have another hdd plugged ?

I didn't see your edits when I  was testing, I'm going to try with ManaGunZ v1.40. Do you think this bug was introduced in 1.39 or 1.40 ?

**Comment by rhynec** [comment]
> Do you think this bug was introduced in 1.39 or 1.40 ?

For my part, I remember that when I tried using the standalone file manager a few versions ago, it always froze when I tried to exit while holding circle. I don't remember the exact version; I'll test a few to see if I can re-create the bug. Maybe it was already fixed.

Yesterday, I also experienced a freeze on the file manager. I was just browsing folders, looking at PARAM.SFOs (the sfo viewer it's very nice, btw; I hadn't tried it out before), and then my system froze when I opened /dev_hdd0/vsh/game_pkg. The folder is empty, and I tested opening it again today and the file manager didn't freeze, so the bug is probably unrelated to the directory itself. Maybe there is a memory leak somewhere in the file manager?

**Comment by Syrus-33** [comment]
> So, i tried with Filemanager 1.40 with usb HDD and an usb stick like 10 times, still not a single freeze. Do you have another hdd plugged ?
> 
> I didn't see your edits when I was testing, I'm going to try with ManaGunZ v1.40. Do you think this bug was introduced in 1.39 or 1.40 ?

Honestly im not sure when the bug was introduced as i just started to use my ps3 again. Previously i was on 4.86 rebug but i just updated to 4.88 evilnat. i then came to see if there was an updated version of managunz. i think it was 1.36 before and i dont remeber having issue.

i updated to managunz 1.4 and it started freezing, then i found this and updated to 1.41 and still the same.

i do not have anything else plugged into the usb.

i enabled the log in managunz but i can seem to find a file of this log??

**Comment by Zarh** [comment]
The freeze isn't related to ntfs but it's when you exit ManaGunZ by holding circle (i always spam)... So maybe it's relatesd to.the holding button...

If i'm able to reproduce the issue, i'll be able to fix it.
The log is /dev_hdd0/tmp/mgz.log

**Comment by Syrus-33** [comment]
Last night I tried using an external hdd instead of my USB stick and I didn't have any issues...it's very wierd.

I also spam O, I don't hold it to exit. It might be an issue with certain usb sticks.

**Comment by Derp0** [comment]
This exact same thing has been happening to me as well, but I just forgot to report it every time.
When this happens I just restart my PS3. This issue is really strange because it happens randomly it seems. After closing the file manager windows and pressing circle one more time to exit the file manager it just freezes. I've tested with 2 different flash drives and 2 different file systems (fat32 and ntfs). Sometimes it works correctly, but once in a while it freezes.

**Comment by Zarh** [comment]
I'll upload a pre-release pkg today.
On this pre-release, the exit will be more talkative (with debug option enabled in settings), with this I'll be able to find the cause of these freeze and hopefully, I'll fix it. I tested over 10 usb hdd/stick and I never had a freeze. But I had lot of this kind a feedback...

**Comment by Zarh** [comment]
it's uploaded : https://github.com/Zarh/ManaGunZ/releases/tag/1.41

**Comment by Syrus-33** [comment]
So i tried the updated release, the stand alone file manager has no issues but when i use the file manager from managunz it froze again when tapping O to close the windows and go back to managunz. it seems to freeze at "finalize_FileExplorer"

Here is the last few lines of my log file, before these lines its just scanning the folders and listing the games so i removed those lines.

Sorting the game list
Get Favorite game list
Installing Dynarec payload
Remove lv2 protection
Get htab r|w|x access
Patch htab
init_FileExplorer
end of init_FileExplorer
start of Open window
End of Open window
start of Open window
End of Open window
Copying...
end_of 'Draw_Copy_screen'
sysThreadExit
finalize_FileExplorer

**Comment by Zarh** [comment]
Oh it's perfect ! Thank you very much. I think it will help me a lot because I was searching somewhere else....

**Comment by Derp0** [comment]
Tested with 1.41:

```

**Comment by Zarh** [comment]
I think I'm finally able to reproduce the issue but it doesn't freeze on my PS3, it's an infinite loading, I can quit with the PS button. So, I have some doubt maybe it's something else. On rpcs3, it's freezing.

Small question just to be sure: do you open 2 window when you make the copy ?

**Comment by rhynec** [comment]
> I think I'm finally able to reproduce the issue but it doesn't freeze on my PS3, it's an infinite loading, I can quit with the PS button. So, I have some doubt maybe it's something else. On rpcs3, it's freezing.
> 
> I think I found the issue and the fix. Small question just to be sure: do you open 2 window when you make the copy/paste ?

Oh, that's probably why I couldn't reproduce the freeze. I was just using a single window each time. I think I did open multiple windows when I experienced all those freezes some time ago.

Well, @Derp0 and @Syrus-33 seem to experience the freezes more often, so waiting for their confirmation would be better. Let's hope that the problem you found is what's causing this issue.

**Comment by Syrus-33** [comment]
> I think I'm finally able to reproduce the issue but it doesn't freeze on my PS3, it's an infinite loading, I can quit with the PS button. So, I have some doubt maybe it's something else. On rpcs3, it's freezing.
> 
> I think I found the issue and the fix. Small question just to be sure: do you open 2 window when you make the copy/paste ?

Yes I do usually open two windows, I never thought of that causing the issue.

**Comment by Zarh** [comment]
me neither, it took me hours to figure it out. The logs you shared helped me a lot ;)

**Comment by Derp0** [comment]
Nice!
On version 1.40 when it freezes I have to restart the PS3, but on v1.41 I can use the PS button to quit.

2 windows, one for the USB and one for hdd0.

**Comment by Zarh** [comment]
fixed with : https://github.com/Zarh/ManaGunZ/commit/2fa3e2cead640e7c16069ce226de4a7e98f399ab#diff-e9ff16be253c848e47832a26c4d275fdd3730e8d15387d77e40518a119a80905R29696
