### ISSUE TITLE
3Dump.bin Generation incorrect

### ISSUE THREAD

**Issue by Dimensional** [Zarh/ManaGunZ#79]
I've run both ManaGunZ 1.40 and 1.41 on my CECH-A01 PS3 running EvilNat 4.88.2 CFW, and both times the app generates the 3Dump.bin file, but it grabs the NAND data from the wrong offset.

The correct offset is suppose to be at `0x00081BA0`, however based on the hex string when comparing it's generated file to my NAND dump, its grabbing from `0x000C1BA0`, which results in a failure when attempting to get the disc key.

I've run this multiple times, again on both versions, and the results have been consistent.

**Comment by Dimensional** [comment]
This is sort of related, but even after placing in the correct 3Dump.bin file, created by following the current Redump guide, when attempting to get the Disc Key in 1.41, the key is different from the official one, or even the one using get_key

The game in question is Metal Gear Solid 4, aka BLUS30109, which I have as part of the Legacy Collection.

Logs from GetKey r2:
```
GetKey r2
Load keys
Test unit ready: return value of ioctl indicates success
Read pic: return value of ioctl indicates success
get dec key
  establish session keys:
    do send key: return value of ioctl indicates success
    do report key: return value of ioctl indicates success
    calculate session keys
    do send key: return value of ioctl indicates success
  get data
    do unknown e1:
    unknown e1 cdb: e10054004ee6564e8dd9fc1c
    return value of ioctl indicates success
    do unknown e0:
    unknown e0 cdb: e00034001ba2073ed0f71570
    return value of ioctl indicates success
get_dec_key succeeded!


disc_key = dcc6a9fe8f5600b24ebba68dd097856b

disc_id = 00000000000000ff0002000000000000
PIC:
10020000444901100000200042444f01
2101030000000000016e961f00100000
00ca73fe000000000000000000000000
00000000000000000000000000000000
00000000444901110001200042444f01
2101030000000000016e961f01358c00
01effffe000000000000000000000000
00000000000000000000000000000000
00000000

SUCCESS: Everything was correctly dumped.
```
Logs from ManaGunZ:
```
GetKey r2
Load keys
Test unit ready: return value of ioctl indicates success
Read pic: return value of ioctl indicates success
get dec key
  establish session keys:
    do send key: return value of ioctl indicates success
    do report key: return value of ioctl indicates success
    calculate session keys
    do send key: return value of ioctl indicates success
  get data
    do unknown e1:
    unknown e1 cdb: e100540017f9eb8a433d5d6f
    return value of ioctl indicates success
    do unknown e0:
    unknown e0 cdb: e0003400f776e4f89f2a1095
    return value of ioctl indicates success
get_dec_key succeeded!


disc_key = d186544a4b014851fef72b3451957570

disc_id = 00000000000000ff0002000000000000
PIC:
10020000444901100000200042444f01
2101030000000000016e961f00100000
00ca73fe000000000000000000000000
00000000000000000000000000000000
00000000444901110001200042444f01
2101030000000000016e961f01358c00
01effffe000000000000000000000000
00000000000000000000000000000000
00000000

SUCCESS: Everything was correctly dumped.
```

**Comment by Bigmanjapan** [comment]
Hello Zarh.

I second what @Dimensional stated in his message regarding retrieving Get Key information.

I have a Slim CECH-2008A with REBUG 4.86 CFW. For my console ManaGunZ creates correct 3Dump.bin (because it's NOR, not NAND?) but still, even with 3Dump.bin being correct, the Gey Key infromation is wrong and doesn't match redump's entries.

On a side note, your erroneous sectors handling works fine. Tested some scratched discs and dumping process terminates as it should upon reaching 30/30 re-tries for an erroneous sector.

**Comment by Bigmanjapan** [comment]
Hello Zarh.

I second what @Dimensional stated in his message regarding Get Key information.

I own a Slim CECH-2008A console modded with REBUG 4.86 CFW. For my console ManaGunZ creates correct 3Dump.bin (because it's NOR, not NAND?) but still, even with 3Dump.bin being correct, the Gey Key infromation is wrong and doesn't match redump's entries.

On a side note, your erroneous sectors handling works fine. Tested some scratched discs and dumping process terminates as it should upon reaching 30/30 re-tries for an erroneous sector.

**Comment by rhynec** [comment]
@Bigmanjapan, GetKey information shoulde be fixed as of [this](https://github.com/Zarh/ManaGunZ/issues/75) commit.

As for 3Dump.bin generation... I've had a few problems with it in the past with retrieving the ERK, though as of now it works properly on my NOR console. So maybe the problem is isolated to NAND?

**Comment by Dimensional** [comment]
> 
> 
> @Bigmanjapan, GetKey information should now be fixed as reported [here](https://github.com/Zarh/ManaGunZ/issues/75) (latest test build doesn't contain the fix).
> 
> As for 3Dump.bin generation... I've had a few problems with it in the past with retrieving the ERK, though as of now it works properly on my NOR console. So maybe the problem is isolated to NAND?

I checked and it appears it's getting the ERK correctly, as that section of 3Dump.bin is correct in addition to finding the EID_Root_key file in the same folder. It's the first half, the part that is generated based on the consoles NAND, that seems to be off.

**Comment by rhynec** [comment]
> > @Bigmanjapan, GetKey information should now be fixed as reported [here](https://github.com/Zarh/ManaGunZ/issues/75) (latest test build doesn't contain the fix).
> > As for 3Dump.bin generation... I've had a few problems with it in the past with retrieving the ERK, though as of now it works properly on my NOR console. So maybe the problem is isolated to NAND?
> 
> I checked and it appears it's getting the ERK correctly, as that section of 3Dump.bin is correct in addition to finding the EID_Root_key file in the same folder. It's the first half, the part that is generated based on the consoles NAND, that seems to be off.
> 
> Edit: I tried compiling it, but I haven't gotten every library for the Open Source PS3 SDK installed, or the extra stuff like Tiny3D yet.
If you've compiled your SDK from the latest source available, do note that some changes in the toolchain seems to have broken PSL1GHT. Use the 2020-07-17 branch from Bucanero (either precompiled or recompile it yourself) to get a working toolchain. You can then use my ps3extralibs repo to get Tiny3D and such (among other things). Or run Bucaneors fork of PS3libraries.

Now, also note that MGZ can't be compiled with latest SDK, due to some changes with gcc 7 (among other things). You need to use older builds like Estwald's PSDK3v2 or Xerpi's Linux build which use gcc 4. Do note that Xerpi's build needs to be run on an older OS to work properly. I've used Xenial on a VM with Ubuntu Xenial, and have gotten succesful MGZ builds.

**Comment by Dimensional** [comment]
I'll have to wait until it's compiled and ready to go. I just tried with a VM and the SDKs and libs you mentioned, and it still failed on the same places. :)

**Comment by rhynec** [comment]
@Dimensional 
It's odd that you're unable to compile Bucanero's toolchain. What error exactly do you get? Anyway, latest toolchain is broken. The latest build that works is [this](https://github.com/bucanero/ps3toolchain/releases/tag/ubuntu-latest-c9b3afc9) one. I recommend just using the pre-compiled one, though you should be able to re-compile it. Anyway, as I mentioned before, you can't build MGZ with this toolchain.

As for Xerpi's build, I meant using the pre-compiled version available [here](https://github.com/xerpi/psl1ght-v2_linux64) instead of using his fork of the toolchain. With this build (on a VM with Xenial), you should be able to compile MGZ.

**Comment by Dimensional** [comment]
> The latest build that works is [this](https://github.com/bucanero/ps3toolchain/releases/tag/ubuntu-latest-c9b3afc9) one. I recommend just using the pre-compiled one, though you should be able to re-compile it. Anyway, as I mentioned before, you can't build MGZ with this toolchain.

I can confirm I was using that exact toolchain, and then pulled from his PS3library repo. Still got errors, which will be listed at the bottom.
> 
> As for Xerpi's build, I meant using the pre-compiled version available [here](https://github.com/xerpi/psl1ght-v2_linux64) instead of using his fork of the toolchain. With this build (on a VM with Xenial), you should be able to compile MGZ. It's 64bit though, so maybe you can't use it?
> 
I'll give that link a shot with my Ubuntu 16.04.7 amd64 VM.

Here's the errors that I get in the build with the newer toolchains, or from Bucanero's. It might be because they still pull from a newer version of PSL1GHT to. Correcting them may result in other errors, and I'm too much of a newb to figure anything out. I just follow instructions like a Happy Computer.

```
/home/USER/src/git/ManaGunZ/MGZ/source/main.c: In function 'GetInfo_JPG':
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3671:9: error: 'jpgDecSource {aka struct _jpgdec_src}' has no member named 'stream'; did you mean 'stream_sel'?
  source.stream = JPGDEC_FILE;
         ^~~~~~
         stream_sel
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3672:19: warning: assignment makes pointer from integer without a cast
-Wint-conversion]
  source.file_name = __get_addr32(path);
                   ^
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3673:9: error: 'jpgDecSource {aka struct _jpgdec_src}' has no member named 'enable'; did you mean 'spu_enable'?
  source.enable = JPGDEC_DISABLE;
         ^~~~~~
         spu_enable
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3673:18: error: 'JPGDEC_DISABLE' undeclared (first use in this function); did you mean 'JPGDEC_FILE'?
  source.enable = JPGDEC_DISABLE;
                  ^~~~~~~~~~~~~~
                  JPGDEC_FILE
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3673:18: note: each undeclared identifier is reported only once for each function it appears in
/home/USER/src/git/ManaGunZ/MGZ/source/main.c:3681:13: error: 'jpgDecThreadInParam {aka struct _jpgdec_thread_in_param}' has no member named 'enable'; did you mean 'spu_enable'?
  InThdParam.enable = 0;
             ^~~~~~
```

**Comment by rhynec** [comment]
> Here's the errors that I get in the build with the newer toolchains, or from Bucanero's. It might be because they still pull from a newer version of PSL1GHT to. Correcting them may result in other errors, and I'm too much of a newb to figure anything out. I just follow instructions like a Happy Computer.
> 
> ```
> 
> ```

Oh, I though you were having trouble building the toolchain, not compiling MGZ. Yeah, there were some changes introduced to PSL1GHT that MGZ doesn't account for. Though, it doesn't really need to. Zar uses PSDK3v2, which is an older build using gcc 4, different jgpdec handling, etc. It's unfortunate that Estwald's SDK is only available on Windows, but Xerpi's build is a close equivalent with minor differences. Latest (working) toolchain should only be necessary to build newer application like PKGi and Apollo.

Do take into account that Xerpi's build, as far as I can tell, doesn't include PS3Soundlib but does include tiny3d. In addition, Xerpi's build uses geohot's tool to sign self, which Estwald changed in PSDK3v2 to scetool. Latest toolchain uses geohot (don't know why they never changed to scetool...). Anyway, since PSDK3v2 uses scetool, projects build with it like MGZ are able to pass in a few flags when compiling that are unavailable to mess with using geohot. So, there may be slight differences in MGZ when building with Xerpi's PSL1GHT. 

I plan to re-create PSDK3v2 for Linux and have it compile on a more recent version of Ubuntu if possible. That way, it will be easier to reliably build projects depending on that older version like MGZ or Irisman.

**Comment by Zarh** [comment]
I'll check this out as soon as possible, sorry for the troubles...

**Comment by Zarh** [comment]
@Dimensional 
I have no idea what's happening, i wrote the good offset, but somehow it's not grabbing the data...

I uploaded the current version : https://github.com/Zarh/ManaGunZ/releases/download/1.41/ManaGunZ_v1.41_2011.pkg

Can you test with this one, I added some log on screen when it create the eid4 (included in the 3dump), this is the 'bad' part of the 3dump.bin

Can you please enable "mgz log", (setting>system>mgz logs) then try to dump the 3DUmp.bin file. You'll have some new log displayed on screen, then go to /dev_hdd0/tmp/mgz.log and copy his content here.

**Comment by Dimensional** [comment]
The following is from the logs, however when comparing the resulting 3Dump.bin file, again it's getting the wrong offset from the NAND, even though it states it's getting the correct offset. Something is causing it to add `0x40000` to the offset when scanning the NAND, which results in it getting the bytes starting at `0xC1BA0` instead of `0x81BA0`. Could it be that the patch, poke or payload for getting the ERK isn't being flushed from memory entirely, or if any of them patch the flash in memory, it's removal is accidentally truncating something or causing the read to offset incorrectly?

```
Dumping the eid_root_key
* install_new_poke
* make_patches
* install_payload
* run_payload
* eid_root_key :
84D3EDA9CEC4258CAE4BDEF040A123AE
5E614C7F446E1E5ACCD420B9F3636E83
C6F867A2C2C45EF62D7E9C6D5CC26A2E
* write eid_root_key
* remove_payload
* remove_new_poke
start_offset 81BA0
sector_id 40D
start_sector_offset 1A0
end_offset 81BD0
end_sector_id 40D
end_sector_offset 1D0
start 1A0
```

**Comment by Zarh** [comment]
ok, I **think** I found the issue, when I wrote the function to get the eid4 I looked at https://www.psdevwiki.com/ps3/Flash#NAND_Flash (i usually use a dump I have): https://www.psdevwiki.com/ps3/Flash#NAND_Flash

this table gives offset with the bootldr (which is 40000), but  when we use sys_storage function it seems to not read the bootldr.
The rebug toobox add an empty area in the place of the bootldr when it dump the flash.
https://github.com/Joonie86/Rebug-Toolbox/blob/master/source/toolbox.cpp#L7446

I'm closing this issue I'm pretty sure it's fixed, now.

Thanks for the feedback !

**Comment by Dimensional** [comment]
Not sure how it's exactly fixed in ManaGunZ. At least we now know why it's getting the wrong offset, but I've been looking over the code and I can't figure out how it does the dump. Searching for `dump_3Dump()` only turns up the function being called, but the function itself isn't located anywhere.

**Comment by Zarh** [comment]
I just uploaded the commit, it wasn't online yet :)

Here it is : https://github.com/Zarh/ManaGunZ/commit/2bf7f31ddf753cdaf6801353b2701be41cb21e8a#diff-e9ff16be253c848e47832a26c4d275fdd3730e8d15387d77e40518a119a80905R16281

dump_3Dump is inside main.c  ;)

**Comment by Dimensional** [comment]
Ah. Github wouldn't show that in the search because it doesn't like large files. Now it tells me. 🤣
